### ISSUE TITLE
Legend on publications page shown below every single publication

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/andersenlab.github.io#3]
The placement of this legend below each publication is redundant: 
![image](https://cloud.githubusercontent.com/assets/1536935/16713875/d738f6d8-4679-11e6-9d2c-2967e10dae3b.png)

A good alternative would be to show a tooltip when hovering over those icons.

Also, I think it would be nice to show citations in the same line as the DOI/Pubmed box (right after it).

**Comment by synmuv** [comment]
My fault. I agree the a tooltip when hovering over the icons will be good. 

I can go either way on moving the citation count.

Some citations still don't have the correct equal contribution notation. 2012 Andersen, Gerke, Shapiro et al. is not correct; and 2015 Etienne and Andersen et al. is not correct. Please check the code that generates the contributions.
