### ISSUE TITLE
Broken links on datasets page

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/andersenlab.github.io#4]
http://andersenlab.org/Research/Data/

Try the second two publications. Thanks!

**Comment by jpr71** [comment]
Yes, for some reason the links work locally but not when pushed.
I'm working on this.

**Comment by synmuv** [comment]
Joshua, please move the QX1430 x CB4856 RIAILs and RIAILs data to the second link (A Powerful...) The RAD-Seq data should be moved to the third link (Chromosome-scale...)

Also, please change authors to un-bold font and add full citation.

**Comment by jpr71** [comment]
Will do!
